

```
`# This is formatted as code`
```

# DATA TYPES AND STRUCTURES

#THEORY QUESTIONS

1.What are data structures, and why are they important?
  >>What Are Data Structures?
A data structure is a way of organizing, storing, and managing data to perform operations efficiently. It defines the relationship between data and the operations that can be performed on it.

  There are two main types of data structures:

- Linear Data Structures – Elements are arranged sequentially.
Examples: Arrays, Linked Lists, Stacks, Queues
- Non-Linear Data Structures – Elements are arranged in a hierarchical or interconnected manner.
Examples: Trees, Graphs, Hash Tables, Heaps

  Why Are Data Structures Important?
- Efficiency – They help in efficiently managing and retrieving data, reducing time and space complexity.
- Scalability – Well-chosen data structures allow applications to handle large amounts of data effectively.
- Better Problem Solving – Many algorithms rely on specific data structures for optimization (e.g., Dijkstra’s algorithm uses priority queues).
- Code Maintainability – Organizing data properly makes code more readable and maintainable.
- Optimized Resource Usage – Proper data structure selection leads to better memory and processing power utilization.

2.Explain the difference between mutable and immutable data types with examples?
  >>- Mutable Data Types
Definition: Mutable objects can be changed after creation without changing their identity (i.e., the memory address remains the same).
Examples:
Lists
Dictionaries
Sets
- Immutable Data Types
Definition: Immutable objects cannot be changed after creation. Any modification creates a new object.
Examples:
Integers
Floats
Tuples
Strings
Booleans

3.What are the main differences between lists and tuples in Python?
  >>Lists
   - Both lists and tuples are used to store collections of items in Python, but they have key differences in behavior and performance.
   Use Lists when you need to modify data frequently (e.g., dynamic collections, sorting, appending).
Use Tuples when you want fixed, unchangeable data (e.g., coordinates, database records, constants).

4.Describe how dictionaries store data ?
  >>Python dictionaries use a hash table with the following process:

  Hashing the Key

- The dictionary computes a hash value (a unique number) for the key using Python’s built-in hash() function.
Finding an Index

- The hash value determines the index in the internal array where the key-value pair is stored.
If two different keys generate the same index (collision), Python uses a collision resolution technique (e.g., open addressing).
Retrieval Process

- When accessing a value using dict[key], Python:
Computes the hash of the key.
Locates the corresponding index.
Returns the associated value in constant time O(1) (on average).

5.Why might you use a set instead of a list in Python?
  >>When to Use a Set Instead of a List
✅ 1. Removing Duplicates Efficiently
Since sets automatically remove duplicates, they are useful for cleaning data.
✅ 2. Faster Membership Checking (in operator)
Sets: O(1) average time complexity (uses a hash table).
Lists: O(n) worst-case time complexity (requires full traversal).
✅ 3. Mathematical Set Operations
Sets support union, intersection, and difference operations.
3. When NOT to Use a Set
❌ Order Matters → Use a list (list maintains insertion order).
❌ Duplicate Elements Are Needed → Lists allow duplicates.
❌ Index-Based Access Required → Sets don’t support indexing (set[0] is invalid).

6. What is a string in Python, and how is it different from a list?
  >>A string in Python is a sequence of characters enclosed in quotes (' or "). It is immutable, meaning it cannot be changed after creation.
  Key Differences with Examples
  - Strings Are Immutable, Lists Are Mutable.
  - Lists Can Store Different Data Types, Strings Cannot.
  ✅ Use a string when working with text-based data (sentences, file paths, etc.).
✅ Use a list when handling collections of different elements (numbers, objects, etc.).

7. How do tuples ensure data integrity in Python?
   >>Tuples in Python are immutable, meaning their values cannot be changed after creation. This immutability provides data integrity by ensuring that the data remains consistent and unchanged throughout a program.

8. What is a hash table, and how does it relate to dictionaries in Python?
  >> A hash table (also known as a hash map) is a data structure that stores key-value pairs using a hash function to compute an index (or address) where values are stored. It allows for fast lookups, insertions, and deletions in average O(1) time complexity.Python dictionaries (dict) are implemented using hash tables. Each dictionary key is hashed, and the hash value determines where the value is stored in memory.

9. Can lists contain different data types in Python?  
  >>Yes! Python lists can hold elements of different data types, including integers, strings, floats, booleans, other lists, tuples, dictionaries, and even functions.

10. Explain why strings are immutable in Python?
  >>Reasons for String Immutability
- Memory Efficiency (String Interning)
Python optimizes memory usage by reusing immutable strings.
If two variables have the same string value, Python points them to the same memory location.
- Hashing and Dictionary Keys
Strings are hashable, allowing them to be used as keys in dictionaries.
Hashing requires fixed (unchangeable) values to ensure consistent lookup times.
- Thread Safety
Since strings cannot be modified, multiple threads can safely share them without synchronization issues.
- Security Benefits
String immutability prevents accidental or malicious modification of critical data, such as passwords.

11.  What advantages do dictionaries offer over lists for certain tasks?
  >>Dictionaries (dict) and lists (list) are both common data structures in Python, but dictionaries are better suited for certain tasks due to their key-value mapping and O(1) lookup speed.

12. Describe a scenario where using a tuple would be preferable over a list?
  >> Scenario Where a Tuple Is Preferable Over a List
Scenario: Storing GPS Coordinates
A tuple is ideal for storing GPS coordinates (latitude, longitude) because these values are fixed and should not be modified.

13. How do sets handle duplicate values in Python?
  >> Sets automatically remove duplicate values when elements are added. This ensures that every element in a set is unique.
  How Sets Work with Duplicates
When adding elements, Python checks for duplicates and only keeps unique values.
If a duplicate is added, it is ignored automatically.

14. How does the “in” keyword work differently for lists and dictionaries?
  >>The in keyword is used to check for membership in both lists and dictionaries, but its behavior differs between these two data structures.
  - Checking Membership in a List
When you use the in keyword with a list, Python checks if the value is present in the list.
It checks for element presence by going through the list and comparing each value.
  - Checking Membership in a Dictionary
When you use the in keyword with a dictionary, it checks for key membership by default, not values.
It checks if the key exists in the dictionary, not whether the value exists.

15.  Can you modify the elements of a tuple? Explain why or why not?
  >> No, you cannot modify the elements of a tuple once it has been created. This is because tuples are immutable in Python.

16.  What is a nested dictionary, and give an example of its use case?  
  >> A nested dictionary in Python is a dictionary where the values are themselves dictionaries. This allows for the representation of complex, hierarchical data structures, where you can store and organize related data under multiple levels of keys.

   Use Case of a Nested Dictionary: Managing Employee Data
   Imagine a company that needs to store information about multiple employees, each of whom may have personal details and work-related information. A nested dictionary can be used to structure this data.

17. Describe the time complexity of accessing elements in a dictionary?
  >> In Python, accessing elements in a dictionary is very efficient, with O(1) time complexity in the average case. This makes dictionaries one of the most efficient data structures for key-value lookups. The O(n) worst-case scenario is rare and usually occurs due to hash collisions, but Python’s hash table implementation is optimized to handle these efficiently.

18.  In what situations are lists preferred over dictionaries?
  >> Both lists and dictionaries are useful, but lists are preferred in certain scenarios where maintaining order, indexing, or simplicity is important.

19. Why are dictionaries considered unordered, and how does that affect data retrieval?
  >>- Conceptual Unorderedness: Dictionaries are unordered collections designed for efficient key-value lookups using hash tables, not for maintaining a specific order.
    - Data Retrieval (O(1)): Accessing data by key is still fast  
     (O(1)) regardless of the insertion order.
    - Insertion Order (Python 3.7+): While dictionaries now
     maintain insertion order in Python 3.7+, their primary design is based on efficient key-value mapping rather than order.

20.  Explain the difference between a list and a dictionary in terms of data retrieval?
  >> The primary difference between a list and a dictionary in terms of data retrieval lies in how the data is stored and accessed.
  - List
  Access by Index: Data in a list is stored in a sequence and can be accessed using a numeric index (an integer representing the position of an element).
  - Dictionary
  Access by Key: In a dictionary, data is stored as key-value pairs. Each value is accessed by its key (which can be a string, number, or any hashable object).

# PRACTICAL QUESTIONS

In [2]:
#1 Write a code to create a string with your name and print it.
# Create a string with my name
my_name = "Vikas Sehgal"

# Print the string
print(my_name)

Vikas Sehgal

In [3]:
#2 Write a code to find the length of the string "Hello World".
# Create the string
my_string = "Hello World"

# Find the length of the string
length_of_string = len(my_string)

# Print the length
print("The length of the string is:", length_of_string)

The length of the string is: 11

In [4]:
#3. Write a code to slice the first 3 characters from the string "Python Programming".
# Create the string
my_string = "Python Programming"

# Slice the first 3 characters
sliced_string = my_string[:3]

# Print the sliced string
print("The first 3 characters are:", sliced_string)

The first 3 characters are: Pyt

In [5]:
#4. Write a code to convert the string "hello" to uppercase.
# Create the string
my_string = "hello"

# Convert the string to uppercase
uppercase_string = my_string.upper()

# Print the uppercase string
print("The string in uppercase is:", uppercase_string)

The string in uppercase is: HELLO

In [6]:
#5.Write a code to replace the word "apple" with "orange" in the string "I like apple".
# Create the string
my_string = "I like apple"

# Replace "apple" with "orange"
new_string = my_string.replace("apple", "orange")

# Print the new string
print("The modified string is:", new_string)

The modified string is: I like orange

In [7]:
#6. Write a code to create a list with numbers 1 to 5 and print it.
# Create a list with numbers from 1 to 5
my_list = [1, 2, 3, 4, 5]

# Print the list
print("The list is:", my_list)

The list is: [1, 2, 3, 4, 5]

In [8]:
#7. Write a code to append the number 10 to the list [1, 2, 3, 4].
 # Create the list
my_list = [1, 2, 3, 4]

# Append the number 10 to the list
my_list.append(10)

# Print the updated list
print("The updated list is:", my_list)

The updated list is: [1, 2, 3, 4, 10]

In [9]:
#8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].
# Create the list
my_list = [1, 2, 3, 4, 5]

# Remove the number 3 from the list
my_list.remove(3)

# Print the updated list
print("The updated list is:", my_list)

The updated list is: [1, 2, 4, 5]

In [10]:
#9.Write a code to access the second element in the list ['a', 'b', 'c', 'd']
# Create the list
my_list = ['a', 'b', 'c', 'd']

# Access the second element (index 1)
second_element = my_list[1]

# Print the second element
print("The second element is:", second_element)

The second element is: b

In [11]:
#10. Write a code to reverse the list [10, 20, 30, 40, 50].
# Create the list
my_list = [10, 20, 30, 40, 50]

# Reverse the list
my_list.reverse()

# Print the reversed list
print("The reversed list is:", my_list)

The reversed list is: [50, 40, 30, 20, 10]

In [12]:
#11.  Write a code to create a tuple with the elements 100, 200, 300 and print it.
# Create the tuple
my_tuple = (100, 200, 300)

# Print the tuple
print("The tuple is:", my_tuple)

The tuple is: (100, 200, 300)

In [13]:
#12.  Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').
# Create the tuple
my_tuple = ('red', 'green', 'blue', 'yellow')

# Access the second-to-last element using negative indexing
second_to_last_element = my_tuple[-2]

# Print the second-to-last element
print("The second-to-last element is:", second_to_last_element)

The second-to-last element is: blue

In [14]:
#13.  Write a code to find the minimum number in the tuple (10, 20, 5, 15).
# Create the tuple
my_tuple = (10, 20, 5, 15)

# Find the minimum number in the tuple
min_number = min(my_tuple)

# Print the minimum number
print("The minimum number is:", min_number)

The minimum number is: 5

In [15]:
#14.  Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
# Create the tuple
my_tuple = ('dog', 'cat', 'rabbit')

# Find the index of the element "cat"
index_of_cat = my_tuple.index('cat')

# Print the index of "cat"
print("The index of 'cat' is:", index_of_cat)

The index of 'cat' is: 1

In [16]:
#15.  Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.
# Create the tuple with three different fruits
fruits_tuple = ('apple', 'banana', 'orange')

# Check if "kiwi" is in the tuple
is_kiwi_in_tuple = 'kiwi' in fruits_tuple

# Print the result
print("Is 'kiwi' in the tuple?", is_kiwi_in_tuple)

Is 'kiwi' in the tuple? False

In [17]:
#16.  Write a code to create a set with the elements 'a', 'b', 'c' and print it.
# Create the set with elements 'a', 'b', 'c'
my_set = {'a', 'b', 'c'}

# Print the set
print("The set is:", my_set)

The set is: {'a', 'c', 'b'}

In [18]:
#17.  Write a code to clear all elements from the set {1, 2, 3, 4, 5}.
# Create the set
my_set = {1, 2, 3, 4, 5}

# Clear all elements from the set
my_set.clear()

# Print the empty set
print("The set after clearing all elements:", my_set)

The set after clearing all elements: set()

In [19]:
#18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.
# Create the set
my_set = {1, 2, 3, 4}

# Remove the element 4 from the set
my_set.remove(4)

# Print the updated set
print("The updated set is:", my_set)

The updated set is: {1, 2, 3}

In [20]:
#19.  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.
# Create the two sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Find the union of the two sets
union_set = set1.union(set2)

# Print the union of the sets
print("The union of the two sets is:", union_set)

The union of the two sets is: {1, 2, 3, 4, 5}

In [21]:
#20.  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.
# Create the two sets
set1 = {1, 2, 3}
set2 = {2, 3, 4}

# Find the intersection of the two sets
intersection_set = set1.intersection(set2)

# Print the intersection of the sets
print("The intersection of the two sets is:", intersection_set)

The intersection of the two sets is: {2, 3}

In [22]:
#21.  Write a code to create a dictionary with the keys "name", "age", and "city", and print it.
# Create the dictionary
my_dict = {
    "name": "John",
    "age": 25,
    "city": "New York"
}

# Print the dictionary
print("The dictionary is:", my_dict)

The dictionary is: {'name': 'John', 'age': 25, 'city': 'New York'}

In [23]:
#22.  Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.
# Create the dictionary
my_dict = {'name': 'John', 'age': 25}

# Add the new key-value pair
my_dict['country'] = 'USA'

# Print the updated dictionary
print("The updated dictionary is:", my_dict)

The updated dictionary is: {'name': 'John', 'age': 25, 'country': 'USA'}

In [24]:
#23.  Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.
# Create the dictionary
my_dict = {'name': 'Alice', 'age': 30}

# Access the value associated with the key "name"
name_value = my_dict['name']

# Print the value
print("The value associated with the key 'name' is:", name_value)

The value associated with the key 'name' is: Alice

In [25]:
#24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.
# Create the dictionary
my_dict = {'name': 'Bob', 'age': 22, 'city': 'New York'}

# Remove the key "age"
del my_dict['age']

# Print the updated dictionary
print("The updated dictionary is:", my_dict)

The updated dictionary is: {'name': 'Bob', 'city': 'New York'}

In [26]:
#25.Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.
# Create the dictionary
my_dict = {'name': 'Alice', 'city': 'Paris'}

# Check if the key "city" exists in the dictionary
key_exists = 'city' in my_dict

# Print the result
print("Does the key 'city' exist in the dictionary?", key_exists)

Does the key 'city' exist in the dictionary? True

In [27]:
#26. Write a code to create a list, a tuple, and a dictionary, and print them all.
# Create the list
my_list = [1, 2, 3, 4, 5]

# Create the tuple
my_tuple = ('apple', 'banana', 'cherry')

# Create the dictionary
my_dict = {'name': 'Alice', 'age': 25, 'city': 'Paris'}

# Print the list, tuple, and dictionary
print("The list is:", my_list)
print("The tuple is:", my_tuple)
print("The dictionary is:", my_dict)

The list is: [1, 2, 3, 4, 5]
The tuple is: ('apple', 'banana', 'cherry')
The dictionary is: {'name': 'Alice', 'age': 25, 'city': 'Paris'}

In [28]:
#27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
#result.(replaced)
import random

# Create a list of 5 random numbers between 1 and 100
random_numbers = [random.randint(1, 100) for _ in range(5)]

# Sort the list in ascending order
random_numbers.sort()

# Print the sorted list
print("The sorted list of random numbers is:", random_numbers)

The sorted list of random numbers is: [21, 22, 24, 58, 96]

In [29]:
#28. Write a code to create a list with strings and print the element at the third index.
# Create the list with strings
my_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']

# Print the element at the third index (index 3)
print("The element at the third index is:", my_list[3])

The element at the third index is: date

In [30]:
#29. Write a code to combine two dictionaries into one and print the result.
# Create the two dictionaries
dict1 = {'name': 'Alice', 'age': 25}
dict2 = {'city': 'Paris', 'country': 'France'}

# Combine the two dictionaries
combined_dict = {**dict1, **dict2}

# Print the combined dictionary
print("The combined dictionary is:", combined_dict)

The combined dictionary is: {'name': 'Alice', 'age': 25, 'city': 'Paris', 'country': 'France'}

In [31]:
#30. Write a code to convert a list of strings into a set.
# Create the list of strings
my_list = ['apple', 'banana', 'cherry', 'apple', 'banana']

# Convert the list into a set
my_set = set(my_list)

# Print the set
print("The set is:", my_set)

The set is: {'banana', 'cherry', 'apple'}